warehouse:
  db_uri: "postgresql://localhost:5432/term-trawler"
vocabularies:
  - vocabulary_id: "SNOMED"
    vocabulary_name: "Systematic Nomenclature of Medicine - Clinical Terms"
    description: "SNOMED CT (Systematized Nomenclature of Medicine Clinical Terms) is a comprehensive clinical terminology used to code, query and analyze health data. The terminology system is maintained and distributed by SNOMED International, the trading name of the International Health Terminology Standards Development Organisation (IHTSDO), established in 2007."
    prefix: "snomedct"
    fhir_system: "http://snomed.info/sct"
    vocabulary_uri: "http://snomed.info/id/[code]"
    archive_filename: "/mnt/c/Users/kerny/Documents/vocabulary_download_v5zip.zip"
    source_type: "OMOP"
  - vocabulary_id: "HPO"
    vocabulary_name: "Human Phenotype Ontology"
    description: "The Human Phenotype Ontology (HPO) aims to provide a standardized vocabulary of phenotypic abnormalities encountered in human disease."
    prefix: "HP"
    fhir_system: "http://human-phenotype-ontology.org"
    vocabulary_uri: "http://purl.obolibrary.org/obo/[code]"
    archive_filename: "/mnt/c/Users/kerny/Documents/vocabulary_download_v5zip.zip"
    source_type: "OMOP"
  - vocabulary_id: "NCIT"
    vocabulary_name: "National Cancer Institute Thesaurus"
    description: "NCI Thesaurus (NCIt) provides reference terminology covering vocabulary for clinical care, translational and basic research, and public information and administrative activities, providing a stable and unique identification code."
    prefix: "NCIT"
    fhir_system: "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl"
    vocabulary_uri: "http://purl.obolibrary.org/obo/[code]"
    archive_filename: "/mnt/c/Users/kerny/Documents/vocabulary_download_v5zip.zip"
    source_type: "OMOP"
  - vocabulary_name: "EDAM - The ontology of data analysis and management"
    description: "EDAM is a comprehensive ontology of well-established, familiar concepts that are prevalent within scientific data analysis and data management (both within and beyond life sciences and imaging)."
    prefix: "edam"
    fhir_system: "http://edamontology.org/EDAM.owl"
    vocabulary_uri: "http://edamontology.org/[code]"
    owl_file: "http://edamontology.org/EDAM.owl" # where to download owl file
    source_type: "OWL"
