[build-system]
requires = ["setuptools>=61.0.0", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "term-trawler"
description = "Terminology collection script"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
    "requests",
    "PyYAML",
    #"oxrdflib",
    "md-terminology-trove",
    "sqlalchemy>=2.0.51",
    "car-utils",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "rich",
    "pytest",
    "rich_argparse",
    "rdflib"
]

[tool.setuptools_scm]
version_file = "src/ttrawler/_version.py"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)

[tool.setuptools.package-data]
"*" = ["*.yaml"]

[tool.uv.sources]
md-terminology-trove = { url = "https://github.com/carrollaboratory/md-terminology-trove/releases/download/v0.2.0/md_terminology_trove-0.2.0-py3-none-any.whl" }
car-utils = { git = "https://github.com/carrollaboratory/car-utils.git" }

[project.scripts]
trawler = "trawler:exec"
